name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build-Demo:
    if: ${{ github.ref == 'refs/heads/demo' }}    
    
    # The type of runner that the job will run on
    runs-on: self-hosted
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get Source
        run: |
          cd /home/ubuntu
          [ -d mrz-scanner-javascript ] && rm -rf mrz-scanner-javascript
          git clone --depth 1 -b demo https://github.com/Dynamsoft/mrz-scanner-javascript.git 

      - name: Prepare Files
        run: |
          # Create a temporary directory for the files to be uploaded
          mkdir -p /home/ubuntu/mrz-scanner-javascript/deploy
          
          # Copy the dist folder
          cp -r /home/ubuntu/mrz-scanner-javascript/dist /home/ubuntu/mrz-scanner-javascript/deploy
          
          # Copy demo and hello world. On demo branch, be sure to update the pathing for the demo
          cp -r /home/ubuntu/mrz-scanner-javascript/samples/demo/* /home/ubuntu/mrz-scanner-javascript/deploy
          cp -r /home/ubuntu/mrz-scanner-javascript/samples/hello-world.html /home/ubuntu/mrz-scanner-javascript/deploy

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_DEMO_SERVER }}
          username: ${{ secrets.FTP_DEMO_USERNAME }}
          password: ${{ secrets.FTP_DEMO_PASSWORD }}
          port: 21 
          local-dir: /home/ubuntu/mrz-scanner-javascript/deploy/
          server-dir: /Demo.dynamsoft.com/mrz-scanner/